"""
Base Strategy
Abstract base class for all trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any


class SignalDirection(Enum):
    """Signal direction."""
    LONG = "long"
    SHORT = "short"
    FLAT = "flat"  # No position / exit


@dataclass
class TradeSignal:
    """
    Signal generated by a strategy.
    
    Contains all information needed to execute or evaluate a trade.
    """
    symbol: str
    direction: SignalDirection
    strategy_name: str
    
    # Price levels
    entry_price: float
    stop_loss: float
    take_profit: Optional[float] = None
    
    # Position sizing inputs
    atr: float = 0.0
    risk_per_share: float = 0.0
    
    # Signal metadata
    signal_strength: float = 1.0  # 0-1 confidence
    conditions_met: int = 0
    total_conditions: int = 0
    
    # Indicator values at signal
    rsi: Optional[float] = None
    bb_position: Optional[float] = None  # % within bands
    adx: Optional[float] = None
    volume_ratio: Optional[float] = None
    
    # Timestamps
    timestamp: datetime = None
    expires_at: Optional[datetime] = None
    
    # Debug info
    reason: str = ""
    indicators: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
        if self.indicators is None:
            self.indicators = {}
    
    @property
    def is_entry(self) -> bool:
        """Check if this is an entry signal."""
        return self.direction in (SignalDirection.LONG, SignalDirection.SHORT)
    
    @property
    def is_exit(self) -> bool:
        """Check if this is an exit signal."""
        return self.direction == SignalDirection.FLAT
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "symbol": self.symbol,
            "direction": self.direction.value,
            "strategy": self.strategy_name,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "signal_strength": self.signal_strength,
            "conditions_met": self.conditions_met,
            "reason": self.reason,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None
        }


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.
    
    All strategies must implement:
    - scan(): Scan for entry signals
    - check_exit(): Check if position should exit
    - get_position_size(): Calculate position size
    """
    
    def __init__(self, name: str):
        """
        Initialize strategy.
        
        Args:
            name: Strategy identifier.
        """
        self.name = name
        self._enabled = True
    
    @property
    def enabled(self) -> bool:
        """Check if strategy is enabled."""
        return self._enabled
    
    def enable(self) -> None:
        """Enable the strategy."""
        self._enabled = True
    
    def disable(self) -> None:
        """Disable the strategy."""
        self._enabled = False
    
    @abstractmethod
    def scan(self, symbols: List[str]) -> List[TradeSignal]:
        """
        Scan symbols for entry signals.
        
        Args:
            symbols: List of symbols to scan.
            
        Returns:
            List of TradeSignal objects for valid entries.
        """
        pass
    
    @abstractmethod
    def check_exit(
        self,
        symbol: str,
        entry_price: float,
        current_price: float,
        stop_loss: float,
        take_profit: Optional[float] = None
    ) -> Optional[TradeSignal]:
        """
        Check if an open position should be exited.
        
        Args:
            symbol: Position symbol.
            entry_price: Entry price of position.
            current_price: Current market price.
            stop_loss: Stop loss price.
            take_profit: Optional take profit price.
            
        Returns:
            TradeSignal with FLAT direction if exit, None otherwise.
        """
        pass
    
    @abstractmethod
    def get_position_size(
        self,
        signal: TradeSignal,
        account_equity: float,
        risk_per_trade: float
    ) -> int:
        """
        Calculate position size for a signal.
        
        Args:
            signal: The trade signal.
            account_equity: Current account equity.
            risk_per_trade: Risk percentage per trade (0.02 = 2%).
            
        Returns:
            Number of shares to trade.
        """
        pass
    
    def validate_signal(self, signal: TradeSignal) -> bool:
        """
        Validate a signal before execution.
        
        Override in subclasses for custom validation.
        
        Args:
            signal: Signal to validate.
            
        Returns:
            True if signal is valid.
        """
        if signal.entry_price <= 0:
            return False
        if signal.stop_loss <= 0:
            return False
        if signal.direction == SignalDirection.LONG:
            if signal.stop_loss >= signal.entry_price:
                return False
        return True
    
    def __repr__(self) -> str:
        status = "enabled" if self._enabled else "disabled"
        return f"<{self.__class__.__name__}(name={self.name}, {status})>"
